stages:
  - build
  - test
  - report

# Step 1: Build Docker Image
build-image:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.12-dind  # Docker-in-Docker for building Docker images
  before_script:
    - apk add --no-cache make  # Ensure 'make' is available
  script:
    - echo "Building Docker image..."
    - make build  # Build the Docker image using Makefile
    - docker save my-test-container:latest -o my-test-container.tar  # Save the image as a tarball
  artifacts:
    paths:
      - my-test-container.tar  # Save the Docker image tarball as an artifact
    expire_in: 1 hour  # You can adjust expiration time as needed

# Step 2: Run Tests in Docker Container
test:
  stage: test
  image: docker:latest
  services:
    - docker:19.03.12-dind  # Docker-in-Docker to run tests in a container
  before_script:
    - apk add --no-cache make  # Ensure 'make' is available
  script:
    - echo "Loading Docker image..."
    - docker load -i my-test-container.tar  # Load the Docker image from the tarball
    - echo "Running tests in Docker container..."
    - make test  # Run tests inside the Docker container
    - ls -R reports  # List the contents of the reports folder to debug if needed
  artifacts:
    paths:
      - reports/**/*  # Save reports (including test results) as artifacts for later use
    expire_in: 1 hour

# Step 3: Install Allure CLI and Generate Report
upload-report:
  stage: report
  image: node:latest  # Use Node.js image for Allure CLI installation
  before_script:
    - echo "Installing Allure CLI..."
    - apt-get update && apt-get install -y unzip wget  # Install dependencies
    - wget https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip  # Download Allure CLI
    - unzip allure-2.17.2.zip -d /opt/  # Unzip Allure CLI
    - ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure  # Add Allure to the system path
  script:
    - echo "Generating Allure Report..."
    - allure generate reports/allure-results --clean -o reports/allure-report  # Generate Allure report
  artifacts:
    paths:
      - reports/allure-report
    expire_in: 1 hour
