stages:
  - test

variables:
  DOCKER_TLS_CERTDIR: ""  # Disables Docker TLS, required for docker:dind

test:
  stage: test
  #image: artifactory:swap:com/docker-local/my-ci-image:latest
  image: docker:latest
  services:
    - docker:dind         # Run Docker daemon as a service

  before_script:
    - apk add --no-cache make

  script:
    - make install

  artifacts:
    paths:
      - reports/allure-report
    expire_in: 1 week
    
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always