name: Docker Test with Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged  # Access to Docker daemon

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Install make and dependencies
      - name: Install make and dependencies
        run: sudo apt-get update && sudo apt-get install -y make curl

      # Step 4: Run Makefile (build and test)
      - name: Run Makefile
        run: make install

      # Step 5: Generate Allure Report from the test results
      - name: Generate Allure Report
        run: docker run --rm \
              -v $(pwd)/reports:/app/reports \
              my-test-container \
              allure generate /app/reports/allure-results --clean -o /app/reports/allure-report

      # Step 6: Debugging: List files in the reports directory (optional)
      - name: List files in reports directory
        run: ls -R reports

      # Step 7: Upload Allure Report as Artifact
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: reports/allure-report
