  name: Docker Test with Allure Report

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

  jobs:
    test:
      runs-on: ubuntu-latest
      services:
        docker:
          image: docker:dind
          options: --privileged # Access to Docker daemon

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Install make
          run: sudo apt-get update && sudo apt-get install -y make

        - name: Run Makefile
          run: make install

        - name: Upload Allure Report as Artifact
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: reports/allure-report


    # Generate Allure Report from the test results
        - name: Generate Allure Report
          run: docker run --rm \
                -v $(pwd)/reports:/app/reports \
                my-test-container \
                allure generate /app/reports/allure-results --clean -o /app/reports/allure-report

        # Debugging: List files in the reports directory
        - name: List files in reports directory
          run: ls -R reports

        # Upload the Allure report as an artifact
        - name: Upload Allure Report as Artifact
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: reports/allure-report