name: Docker Test with Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged  # Access to Docker daemon

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Install make and dependencies
      - name: Install make and dependencies
        run: sudo apt-get update && sudo apt-get install -y make curl

      # Step 4: Build Docker image and run tests
      - name: Build Docker image
        run: docker build -t my-test-container .

      - name: Run tests with pytest (Generate Allure results)
        run: docker run --rm -v $(pwd)/reports:/app/reports my-test-container

      # Step 5: Install Allure command-line tool
      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip
          unzip allure-2.17.2.zip -d /opt/
          sudo ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure

      # Step 6: Generate Allure Report from the test results
      - name: Generate Allure Report
        run: allure generate reports/allure-results --clean -o reports/allure-report

      # Step 7: Debugging: List files in the reports directory (optional)
      - name: List files in reports directory
        run: ls -R reports

      # Step 8: Upload Allure Report as Artifact
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: reports/allure-report
